### ISSUE TITLE
RPI2 - missing required signature

### ISSUE THREAD

**Issue by jfeldis** [indiebox/ubos-admin#51] opened 2015-02-26 19:59 UTC
Installed image  ubos_red_rpi2_20150224-033232.img.xz  on RPI2 and booted up.  Tried to install owncloud via 
  ubos-admin createsite  
  App to run: owncloud
Downloading packages...
ERROR: FATAL: Failed to install package(s). Pacman says: error: os: missing required signature

ubos-admin update  results in a similar list of errors
error: os: missing required signature

**Comment by indiebox** [comment] 2015-02-26 20:01
Could you check whether your system is fully "up" with:

    systemctl is-system-running

and if not, report which services are hung if there are any? Another thing to do would be to run

    pacman-key --populate archlinuxarm
    pacman-key --populate ubos

and try again.

**Comment by jfeldis** [comment] 2015-02-26 20:08
system is running, no hangs resported
i get errors from the pacman-key commands
---------------------------------------------------------------------------
[root@ubos-raspberry-pi2 ~]# systemctl is-system-running
running
[root@ubos-raspberry-pi2 ~]# pacman-key --populate archlinuxarm
==> Appending keys from archlinuxarm.gpg...
gpg: Fatal: /etc/pacman.d/gnupg/trustdb.gpg: invalid trustdb
==> Locally signing trusted keys in keyring...
  -> Locally signing key 02922214DE8981D14DC2ACABBC704E86B823CD25...
==> ERROR: 02922214DE8981D14DC2ACABBC704E86B823CD25 could not be locally signed.
  -> Locally signing key 69DD6C8FD314223E14362848BF7EEF7A9C6B5765...
==> ERROR: 69DD6C8FD314223E14362848BF7EEF7A9C6B5765 could not be locally signed.
  -> Locally signing key 9D22B7BB678DC056B1F7723CB55C5315DCD9EE1A...
==> ERROR: 9D22B7BB678DC056B1F7723CB55C5315DCD9EE1A could not be locally signed.
[root@ubos-raspberry-pi2 ~]# pacman-key --populate ubos
==> Appending keys from ubos.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key CF9DC152CFE2C869FC83C40C64FCC512CBC35F22...
==> ERROR: CF9DC152CFE2C869FC83C40C64FCC512CBC35F22 could not be locally signed.
[root@ubos-raspberry-pi2 ~]# systemctl is-system-running                                         running
[root@ubos-raspberry-pi2 ~]# [root@ubos-raspberry-pi2 ~]# ubos-admin createsite                  -bash: [root@ubos-raspberry-pi2: command not found
[root@ubos-raspberry-pi2 ~]# ubos-admin createsite
App to run: owncloud
Downloading packages...
ERROR: FATAL: Failed to install package(s). Pacman says: error: os: missing required signature
error: hl: missing required signature
error: tools: missing required signature
error: database 'os' is not valid (invalid or corrupted database (PGP signature))
error: database 'hl' is not valid (invalid or corrupted database (PGP signature))
error: database 'tools' is not valid (invalid or corrupted database (PGP signature))
--------------------------------------------------------------------------------------------

**Comment by indiebox** [comment] 2015-02-26 22:50
I can reproduce, and it's not specific to the Raspberry Pi 2: On the first boot, ubos-admin is attempting to import and locally sign the package keys from the Arch Linux ARM guys and the UBOS buildmaster key. This fails because:

    gpg: key .... was created 462929217 seconds in the future (time warp or clock problem)

and that's because at that time, the device (which doesn't have a real-time clock, and even if it did, it may be incorrect) hasn't connected to the network yet and gotten the correct time. There's already a hack in the code to avoid that, but apparently the hack isn't good enough: https://github.com/indiebox/ubos-admin/blob/master/ubos-admin/vendor_perl/UBOS/Host.pm#L578

**Comment by jfeldis** [comment] 2015-02-27 20:04
The device booted 1970-01-01, but appears to get the current time before the gpg logs start

[root@ubos-raspberry-pi2 ~]# journalctl -b
-- Logs begin at Thu 1970-01-01 00:00:06 UTC, end at Fri 2015-02-27 19:55:13 UTC
Jan 01 00:00:06 ubos-raspberry-pi2 systemd-journal[155]: Runtime journal is usin
.......................................................................
time change and then gpg messages:

Jan 01 00:00:12 ubos-raspberry-pi2 systemd[1]: Starting ubos-admin configuration...
Jan 01 00:00:12 ubos-raspberry-pi2 ubos-admin[249]: Starting ubos-admin.service
Jan 01 00:00:14 ubos-raspberry-pi2 ubos-admin[251]: slurpFile( /etc/os-release )
Jan 01 00:00:14 ubos-raspberry-pi2 ubos-admin[251]: Exec: date 022403362015.54
Feb 24 03:36:54 ubos-raspberry-pi2 ubos-admin-initialize[251]: Tue Feb 24 03:36:54 UTC 2015
Feb 24 03:36:54 ubos-raspberry-pi2 ubos-admin[251]: Exec: pacman-db-upgrade
Feb 24 03:36:54 ubos-raspberry-pi2 systemd[1]: Time has been changed
Feb 24 03:36:54 ubos-raspberry-pi2 systemd[1]: Starting Rotate log files...
Feb 24 03:36:54 ubos-raspberry-pi2 systemd[1]: Starting Verify integrity of password and group files...
Feb 24 03:36:54 ubos-raspberry-pi2 systemd[1]: Started Rotate log files.
Feb 24 03:36:54 ubos-raspberry-pi2 ubos-admin[251]: Exec: pacman-key --init
Feb 24 03:36:54 ubos-raspberry-pi2 systemd[1]: Started Verify integrity of password and group files.
Feb 24 03:36:54 ubos-raspberry-pi2 ubos-admin-initialize[251]: gpg: starting migration from earlier GnuPG versions
Feb 24 03:36:55 ubos-raspberry-pi2 ubos-admin-initialize[251]: gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-
Feb 24 03:36:55 ubos-raspberry-pi2 ubos-admin-initialize[251]: gpg: migration succeeded
Feb 24 03:36:55 ubos-raspberry-pi2 ubos-admin-initialize[251]: gpg: Fatal: /etc/pacman.d/gnupg/trustdb.gpg: invalid trustdb
Feb 24 03:36:55 ubos-raspberry-pi2 ubos-admin-initialize[251]: gpg: Generating pacman keyring master key...
Feb 24 03:36:55 ubos-raspberry-pi2 ssh-keygen[203]: ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519
Feb 24 03:36:55 ubos-raspberry-pi2 systemd[1]: Started SSH Key Generation.
Feb 24 03:37:01 ubos-raspberry-pi2 ubos-admin-initialize[251]: gpg: Fatal: /etc/pacman.d/gnupg/trustdb.gpg: invalid trustdb
Feb 24 03:37:01 ubos-raspberry-pi2 ubos-admin-initialize[251]: ==> Updating trust database...
Feb 24 03:37:01 ubos-raspberry-pi2 ubos-admin-initialize[251]: gpg: Fatal: /etc/pacman.d/gnupg/trustdb.gpg: invalid trustdb
Feb 24 03:37:01 ubos-raspberry-pi2 ubos-admin-initialize[251]: ==> ERROR: Trust database could not be updated.
Feb 24 03:37:01 ubos-raspberry-pi2 ubos-admin[251]: Exec: pacman -Q archlinux-keyring    > /dev/null 2>&1 && pacman-key --populate arc
Feb 24 03:37:32 ubos-raspberry-pi2 ubos-admin[251]: slurpFile( /tmp/JhMruTbNYJ )
Feb 24 03:37:32 ubos-raspberry-pi2 ubos-admin[251]: Exec: pacman -Q archlinuxarm-keyring > /dev/null 2>&1 && pacman-key --populate arc
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: ==> Appending keys from archlinuxarm.gpg...
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: ==> Locally signing trusted keys in keyring...
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: -> Locally signing key 02922214DE8981D14DC2ACABBC704E86B823CD25...
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: -> Locally signing key 69DD6C8FD314223E14362848BF7EEF7A9C6B5765...
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: -> Locally signing key 9D22B7BB678DC056B1F7723CB55C5315DCD9EE1A...
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin[251]: slurpFile( /tmp/AmnVNqsu0N )
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin[251]: Exec: pacman-key --populate ubos
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: ==> Appending keys from ubos.gpg...
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: gpg: Fatal: /etc/pacman.d/gnupg/trustdb.gpg: invalid trustdb
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: ==> Locally signing trusted keys in keyring...
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: -> Locally signing key CF9DC152CFE2C869FC83C40C64FCC512CBC35F22...
Feb 24 03:38:03 ubos-raspberry-pi2 ubos-admin-initialize[251]: ==> ERROR: CF9DC152CFE2C869FC83C40C64FCC512CBC35F22 could not be locall

**Comment by indiebox** [comment] 2015-03-11 17:14
I'm closing this because the time heuristics have been adjusted and it hasn't occurred since. We can reopen if it reoccurs.

**Closed by indiebox** 2015-03-11 17:14 UTC
